name: Periodic run
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main
jobs:
  scrapper:
    name: Starting environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout main branch

      - run: npm install
        name: Install packages

      - run: npm start
        name: Start the scrapping process
