name: Periodic run
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main
jobs:
  scrapper:
    name: Starting environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout main branch

      - run: npm install
        name: Install packages

      - run: npm start
        name: Start the scrapping process

      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      # upload scrapped data
      - uses: actions/upload-artifact@v3
        name: Upload scrapped data
        with:
          name: scrapped-data
          path: road_signs.json
